### ISSUE TITLE
vimdoc can't generate codefmtlib docs

### ISSUE THREAD

**Issue by dbarnett** [google/vim-codefmt#1]
If I try to generate the codefmtlib docs with vimdoc, I get an AssertionError about line length:
```
Traceback (most recent call last):
  File "/usr/bin/vimdoc", line 5, in <module>
    vimdoc.__main__.main()
  File "/usr/lib/python3/dist-packages/vimdoc/__main__.py", line 19, in main
    Helpfile(module, docdir).Write()
  File "/usr/lib/python3/dist-packages/vimdoc/output.py", line 28, in Write
    self.WriteHeader()
  File "/usr/lib/python3/dist-packages/vimdoc/output.py", line 42, in WriteHeader
    self.Print(line)
  File "/usr/lib/python3/dist-packages/vimdoc/output.py", line 172, in Print
    assert len(line) <= self.WIDTH
AssertionError
```

This is because the description field in addon-info.json is too long and triggers google/vimdoc#82. It's probably worth shortening up the description, regardless of what happens with the vimdoc bug, and leaving the detailed explanation for the intro section.

**Comment by dbarnett** [comment]
Moved to google/vim-codefmtlib#3.
